import Head from "next/head";

export default function Home() {
  return (
    <div className="bg-gray-100 h-screen">
      <Head>
        <title>Youtube Subscription Organizer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <h1 className="text-6xl sm:text-7xl text-black text-center">
          Youtube Subscription Organizer
        </h1>
      </main>
    </div>
  );
}
